---

- hosts: all                                             # "all" targets all devices in the inventory
  become: true
  pre_tasks:                                             # pre-tasks demands to be run before tasks

  - name: updating repositories (Debian/Ubuntu)...       # Name of the task, can be anything you like
    tags: always
    apt:                                                 # focusing on apt package manager 
      update_cache: yes                                  # task for updating the repository
    changed_when: false                                  # this means it will not consider it a change 
                                                         # when the cache has been updated
    when: ansible_distribution in ["Debian", "Ubuntu"]   # condition looking for distro

  - name: updating repositories (RedHat/Centos)...       # Name of the task, can be anything you like
    tags: always
    dnf:                                                 # focusing on dnf package manager 
      update_cache: yes                                  # task for updating the repository
    changed_when: false                                  # this means it will not consider it a change 
                                                         # when the cache has been updated
    when: ansible_distribution in ["RedHat", "Centos"]   # condition looking for distro

      
- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: database_servers
  become: true
  roles:
    - database_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers
