- name: install nginx and php packages...              # task name, can be anything
  tags: nginx,debian
  package:                                             # focusing on apt package manager
    name:                                              # name section for all packages that should be inst.
      - "{{ nginx_package_name  }}"                    # package name
      - "{{ php_package_name  }}"                      # package name
      - "{{ php_mariadb_package_name }}"               # package name
    state: latest                                      # referres to version 
      #  when: ansible_distribution in ["Debian","Ubuntu"]    # condition looking for distro

- name: starting & enabling nginx Web-Server...
  tags: nginx,debian
  service:
    name: "{{ nginx_service_name }}"
    state: started
    enabled: yes
      #  when: ansible_distribution == "Debian"

- name: changing log file...                 
  tags: nginx,debian
  lineinfile:                                          # working with a line in a file module
    path: /etc/nginx/nginx.conf                        # path to the file that needs change
    regexp: '^error_log'                               # Regular expressaion to locate line in file
    line: error_log /var/log/nginx/error-default.log;  # How the line should look like or replace with
      #  when: ansible_distribution == "Debian"
  notify: restart_nginx 

- name: uploading default html file...
  tags: nginx,webserver                                # tagging to focus installation
  copy:                                                # copying files to server/workstation
    src: default_site.html
    dest: /var/www/html/index.html
    owner: nobody
    group: nogroup
    mode: 0644
