- name: installing MariaDB Server (Debian/Ubuntu)...
  tags: db,mariadb,debian
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: installing MariaDB Server (Red Hat/Centos)...
  tags: db,mariadb,redhat
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution in ["RedHat", "Centos"]
