- name: restart_nginx
  service:                                             # using the Service module
    name: "{{ nginx_service_name }}"                   # looking for nginx service
    state: restarted                                   # restart the service
